language: rust
rust:
- stable
- nightly
- beta
node_js:
- "10"
matrix:
  allow_failures:
  - rust: stable
  fast_finish: true
cache: cargo
before_install:
- npm install
script: |
  cargo build --verbose
  cargo test
  npm test
