language: rust
rust:
- stable
- nightly
- beta
matrix:
  allow_failures:
  - rust: stable
  fast_finish: true
cache: cargo
before_install:
- nvm install 10
- npm install
script: |
  cargo build --verbose
  cargo test
  npm test
